<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>FloorPlanGeneratorTests</AssemblyName>
    <RootNamespace>FloorPlanGeneratorTests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="RhinoCommon">
      <HintPath>../libs/RhinoCommon.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="Grasshopper">
      <HintPath>../libs/Grasshopper.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="GH_IO">
      <HintPath>../libs/GH_IO.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="clipper_library">
      <HintPath>../libs/clipper_library.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Magnetizing_FPG">
      <HintPath>../build/net48/Magnetizing_FPG.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

  <!-- Copy native Rhino DLLs to output directory -->
  <ItemGroup>
    <None Include="C:\Program Files\Rhino 7\System\rhcommon_c.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="C:\Program Files\Rhino 7\System\rhcommonrdk_c.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="C:\Program Files\Rhino 7\Plug-ins\Grasshopper\GH_Util.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="C:\Program Files\Rhino 7\System\Eto.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="C:\Program Files\Rhino 7\System\Eto.Wpf.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>