<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Exe</OutputType>
    <AssemblyName>Magnetizing_FPG.Tests</AssemblyName>
    <RootNamespace>Magnetizing_FPG.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\src\Magnetizing_FPG.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="RhinoCommon">
      <HintPath>..\libs\RhinoCommon.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="GH_IO">
      <HintPath>..\libs\GH_IO.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Grasshopper">
      <HintPath>..\libs\Grasshopper.dll</HintPath>
      <Private>True</Private>
    </Reference>
  </ItemGroup>

  <Target Name="CopyDependencies" AfterTargets="Build">
    <ItemGroup>
      <LibrariesToCopy Include="..\libs\*.dll" />
    </ItemGroup>
    <Copy SourceFiles="@(LibrariesToCopy)" DestinationFolder="$(OutputPath)" SkipUnchangedFiles="true" />
  </Target>

</Project>